#!/usr/bin/env python3
"""Visual preview of the new side-by-side layout."""

print("🎨 NEW LAYOUT PREVIEW")
print("=" * 80)
print("")

print("📊 File & Header Information")
print("┌" + "─" * 78 + "┐")
print("│" + " " * 78 + "│")
print("│  📊 File Information" + " " * 23 + "│  📋 Header Information" + " " * 20 + "│")
print("│  📁 File: sample_payroll.xlsx" + " " * 9 + "│  📅 Date: 01-04-2025" + " " * 19 + "│")  
print("│  📏 Total Rows: 11" + " " * 22 + "│  🏢 Company: LIGHT" + " " * 20 + "│")
print("│  📐 Total Columns: 10" + " " * 18 + "│  🏦 Account: Cash" + " " * 22 + "│")
print("│" + " " * 78 + "│")
print("└" + "─" * 78 + "┘")
print("")

print("✅ BENEFITS OF NEW LAYOUT:")
print("   🔹 Better space utilization - information fits in one compact box")
print("   🔹 Easier to scan - related information is grouped together") 
print("   🔹 More room for data tables below")
print("   🔹 Cleaner, more professional appearance")
print("")

print("📐 OLD LAYOUT (Before):")
print("   ┌── 📊 File Information ────────────┐")
print("   │ 📁 File: sample_payroll.xlsx     │")  
print("   │ 📏 Total Rows: 11               │")
print("   │ 📐 Total Columns: 10            │")
print("   └─────────────────────────────────┘")
print("")
print("   ┌── 📋 Header Information ──────────┐")
print("   │ 📅 Date: 01-04-2025            │")
print("   │ 🏢 Company: LIGHT              │") 
print("   │ 🏦 Account: Cash               │")
print("   └─────────────────────────────────┘")
print("")

print("📐 NEW LAYOUT (After - Side by Side):")
print("   ┌── 📊 File & Header Information ────────────────────────┐")
print("   │ 📊 File Information    │  📋 Header Information        │")
print("   │ 📁 File: sample.xlsx   │  📅 Date: 01-04-2025         │")
print("   │ 📏 Total Rows: 11      │  🏢 Company: LIGHT           │")
print("   │ 📐 Total Columns: 10   │  🏦 Account: Cash            │")
print("   └────────────────────────────────────────────────────────┘")
print("")

print("🚀 The new layout saves vertical space and looks more organized!")